export const hexTable = [
	{
		key: "111111",
		hex: "\u4DC0",
		name: "Ch’ien",
		character: "\u4E7E",
		title: "The Creative",
		judgement:
			"The movement of heaven is full of power. THE CREATIVE works sublime success, Furthering through perseverance",
		image: "Thus the superior man makes himself strong and untiring. The doubling of the trigram Ch’ien, the Creative, gives the image of powerful and constantly repeated movement. The doubling suggests that one draws strength from within oneself, and that after each action a new one follows, without cease.",
	},
	{
		key: "000000",
		hex: "\u4DC1",
		name: "K'un",
		character: "\u5764",
		title: "The Receptive",
		judgement:
			"THE RECEPTIVE brings about sublime success, Furthering through the perseverance of a mare. If the superior man undertakes something and tries to lead, He goes astray; But if he follows, he finds guidance. It is favorable to find friends in the west and south, To forego friends in the east and north. Quiet perseverance brings good fortune.",
		image: "The earth’s condition is receptive devotion. Thus the superior man who has breadth of character carries the outer world.",
	},
	{
		key: "100010",
		hex: "\u4DC2",
		name: "Chun",
		character: "\u5C6F",
		title: "Difficulty at the Beginning",
		judgement:
			"Difficulty at the Beginning works supreme success, Furthering through perseverance. Nothing should be undertaken. It furthers one to appoint helpers.",
		image: "Clouds and thunder: The image of Difficulty at the Beginning. Thus the superior man Brings order out of confusion",
	},
	{
		key: "010001",
		hex: "\u4DC3",
		name: "Me\u0302ng",
		character: "\u8499",
		title: "Youthful Folly",
		judgement:
			"YOUTHFUL FOLLY has success. It is not I who seek the young fool; The young fool seeks me. At the first oracle I inform him. If he asks two or three times, it is importunity. If he importunes, I give him no information. Perseverance furthers.",
		image: "A spring wells up at the foot of the mountain: The image Of YOUTH. Thus the superior man fosters his character By thoroughness in all that he does.",
	},
	{
		key: "111010",
		hex: "\u4DC4",
		name: "Hsu\u0308",
		character: "\u9700",
		title: "Waiting (Nourishment)",
		judgement:
			"WAITING. If you are sincere, You have light and success. Perseverance brings good fortune. It furthers one to cross the great water.",
		image: "Clouds rise up to heaven: The image of WAITING. Thus the superior man eats and drinks, Is joyous and of good cheer.",
	},
	{
		key: "010111",
		hex: "\u4DC5",
		name: "Sung",
		character: "\u8A1F",
		title: "Conflict",
		judgement:
			"CONFLICT. You are sincere And are being obstructed. A cautious halt halfway brings good fortune. Going through to the end brings misfortune. It furthers one to see the great man. It does not further one to cross the great water",
		image: "Heaven and water go their opposite ways: The image of CONFLICT. Thus in all his transactions the superior man Carefully considers the beginning",
	},
	{
		key: "010000",
		hex: "\u4DC6",
		name: "Shih",
		character: "\u5E2B",
		title: "The Army (Leading)",
		judgement:
			"When there is conflict, the masses are sure to rise up. Hence there follows the hexagram of THE ARMY. Army means mass.",
		image: "In the middle of the earth is water: The image of THE ARMY. Thus the superior man increases his masses By generosity toward the people.",
	},
	{
		key: "000010",
		hex: "\u4DC7",
		name: "Pi",
		character: "\u6BD4",
		title: "Holding Together",
		judgement:
			"HOLDING TOGETHER brings good fortune. Inquire of the oracle once again Whether you possess sublimity, constancy, and perseverance; Then there is no blame. Those who are uncertain gradually join. Whoever comes too late Meets with misfortune.",
		image: "On the earth is water: The image of HOLDING TOGETHER. Thus the kings of antiquity Bestowed the different states as fiefs And cultivated friendly relations With the feudal lords.",
	},
	{
		key: "111011",
		hex: "\u4DC8",
		name: "Hsiao Ch'u",
		character: "\u5C0F \u755C",
		title: "The Taming Power of the Small",
		judgement:
			"THE TAMING POWER OF THE SMALL Has success. Dense clouds, no rain from our western region.",
		image: "The wind drives across heaven: The image of THE TAMING POWER OF THE SMALL. Thus the superior man Refines the outward aspect of his nature.",
	},
	{
		key: "110111",
		hex: "\u4DC9",
		name: "Lu\u0308",
		character: "\u5C65",
		title: "Treading (Conduct)",
		judgement:
			"TREADING. Treading upon the tail of the tiger. It does not bite the man. Success.",
		image: "Heaven above, the lake below: The image of TREADING. Thus the superior man discriminates between high and low, And thereby fortifies the thinking of the people",
	},
	{
		key: "000111",
		hex: "\u4DCA",
		name: "T'ai",
		character: "\u6CF0",
		title: "Peace",
		judgement:
			"PEACE. The small departs, The great approaches. Good fortune. Success.",
		image: "Heaven and earth unite: the image of PEACE. Thus the ruler Divides and completes the course of heaven and earth; He furthers and regulates the gifts of heaven and earth, And so aids the people.",
	},
	{
		key: "111000",
		hex: "\u4DCB",
		name: "P'i",
		character: "\u5426",
		title: "Standstill (Stagnation)",
		judgement:
			"STANDSTILL. Evil people do not further The perseverance of the superior man. The great departs; the small approaches.",
		image: "Heaven and earth do not unite: The image of STANDSTILL. Thus the superior man falls back upon his inner worth In order to escape the difficulties. He does not permit himself to be honored with revenue.",
	},
	{
		key: "101111",
		hex: "\u4DCC",
		name: "T'ung Je\u0302n",
		character: "\u540C \u4EBA",
		title: "Fellowship with Men",
		judgement:
			"FELLOWSHIP WITH MEN in the open. Success. It furthers one to cross the great water. The perseverance of the superior man furthers.",
		image: "Heaven together with fire: The image of FELLOWSHIP WITH MEN. Thus the superior man organizes the clans And makes distinctions between things.",
	},
	{
		key: "111101",
		hex: "\u4DCD",
		name: "Ta Yu",
		character: "\u5927 \u6709",
		title: "Posession in Great Measure",
		judgement: "POSSESSION IN GREAT MEASURE. Supreme success.",
		image: "Fire in heaven above: The image of POSSESSION IN GREAT MEASURE. Thus the superior man curbs evil and furthers good, And thereby obeys the benevolent will of heaven.",
	},
	{
		key: "001000",
		hex: "\u4DCE",
		name: "Ch'ien",
		character: "\u8B19",
		title: "Modesty",
		judgement:
			"MODESTY creates success. The superior man carries things through.",
		image: "Within the earth, a mountain: The image of MODESTY. Thus the superior man reduces that which is too much, And augments that which is too little. He weighs things and makes them equal.",
	},
	{
		key: "000100",
		hex: "\u4DCF",
		name: "Yu\u0308",
		character: "\u8C6B",
		title: "Enthusiasm",
		judgement:
			"ENTHUSIASM. It furthers one to install helpers And to set armies marching.",
		image: "Thunder comes resounding out of the earth: The image of ENTHUSIASM. Thus the ancient kings made music In order to honor merit, And offered it with splendor To the Supreme Deity, Inviting their ancestors to be present.",
	},
	{
		key: "100110",
		hex: "\u4DD0",
		name: "Sui",
		character: "\u96A8",
		title: "Following",
		judgement:
			"FOLLOWING has supreme success. Perseverance furthers. No blame.",
		image: "Thunder in the middle of the lake: The image of FOLLOWING. Thus the superior man at nightfall Goes indoors for rest and recuperation.",
	},
	{
		key: "011001",
		hex: "\u4DD1",
		name: "Ku",
		character: "\u8831",
		title: "Work on what has been Spoiled/Decay",
		judgement:
			"WORK ON WHAT HAS BEEN SPOILED Has supreme success. It furthers one to cross the great water. Before the starting point, three days. After the starting point, three days.",
		image: "The wind blows low on the mountain: The image of DECAY. Thus the superior man stirs up the people And strengthens their spirit.",
	},
	{
		key: "110000",
		hex: "\u4DD2",
		name: "Lin",
		character: "\u81E8",
		title: "Approach",
		judgement:
			"APPPROACH has supreme success. Perseverance furthers. When the eighth month comes, There will be misfortune.",
		image: "The earth above the lake: The image of APPROACH. Thus the superior man is inexhaustible In his will to teach, And without limits In his tolerance and protection of the people.",
	},
	{
		key: "000011",
		hex: "\u4DD3",
		name: "Kuan",
		character: "\u89C0",
		title: "Contemplation (View)",
		judgement:
			"CONTEMPLATION. The ablution has been made, But not yet the offering. Full of trust they look up to him.",
		image: "The wind blows over the earth: The image of CONTEMPLATION. Thus the kings of old visited the regions of the world, Contemplated the people, And gave them instruction.",
	},
	{
		key: "100101",
		hex: "\u4DD4",
		name: "Shih Ho",
		character: "\u566C \u55D1",
		title: "Biting Through",
		judgement:
			"BITING THROUGH has success. It is favorable to let justice be administered.",
		image: "Thunder and lightning: The image of BITING THROUGH. Thus the kings of former times made firm the laws Through clearly defined penalties.",
	},
	{
		key: "101001",
		hex: "\u4DD5",
		name: "Pi",
		character: "\u8CC1",
		title: "Grace",
		judgement:
			"GRACE has success. In small matters It is favorable to undertake something.",
		image: "Fire at the foot of the mountain: The image of GRACE. Thus does the superior man proceed When clearing up current affairs. But he dare not decide controversial issues in this way.",
	},
	{
		key: "000001",
		hex: "\u4DD6",
		name: "Po",
		character: "\u525D",
		title: "Splitting Apart",
		judgement: "SPLITTING APART. It does not further one To go anywhere.",
		image: "The mountain rests on the earth: The image of SPLITTING APART. Thus those above can ensure their position Only by giving generously to those below.",
	},
	{
		key: "100000",
		hex: "\u4DD7",
		name: "Fu",
		character: "\u5FA9",
		title: "Return (The Turning Point)",
		judgement:
			"RETURN. Success. Going out and coming in without error. Friends come without blame. To and fro goes the way. On the seventh day comes return. It furthers one to have somewhere to go.",
		image: "Thunder within the earth: The image of THE TURNING POINT. Thus the kings of antiquity closed the passes At the time of solstice. Merchants and strangers did not go about, And the ruler Did not travel through the provinces.",
	},
	{
		key: "100111",
		hex: "\u4DD8",
		name: "Wu Wang",
		character: "\u7121 \u5984",
		title: "Innocence (The Unexpected)",
		judgement:
			"INNOCENCE. Supreme success. Perseverance furthers. If someone is not as he should be, He has misfortune, And it does not further him To undertake anything.",
		image: "Under heaven thunder rolls: All things attain the natural state of innocence. Thus the kings of old, Rich in virtue, and in harmony with the time, Fostered and nourished all beings.",
	},
	{
		key: "111001",
		hex: "\u4DD9",
		name: "Ta Ch'u",
		character: "\u5927 \u755C",
		title: "The Taming Power of the Great",
		judgement:
			"THE TAMING POWER OF THE GREAT. Perseverance furthers. Not eating at home brings good fortune. It furthers one to cross the great water.",
		image: "Heaven within the mountain: The image of THE TAMING POWER OF THE GREAT. Thus the superior man acquaints himself with many sayings of antiquity And many deeds of the past, In order to strengthen his character thereby.",
	},
	{
		key: "100001",
		hex: "\u4DDA",
		name: "I",
		character: "\u9824",
		title: "The Corners of the Mouth",
		judgement:
			"THE CORNERS OF THE MOUTH. Perseverance brings good fortune. Pay heed to the providing of nourishment And to what a man seeks To fill his own mouth with.",
		image: "At the foot of the mountain, thunder: The image of PROVIDING NOURISHMENT. Thus the superior man is careful of his words And temperate in eating and drinking.",
	},
	{
		key: "011110",
		hex: "\u4DDB",
		name: "Ta Kuo",
		character: "\u5927 \u904E",
		title: "Preponderance of the Great",
		judgement:
			"PREPONDERANCE OF THE GREAT. The ridgepole sags to the breaking point. It furthers one to have somewhere to go. Success.",
		image: "The lake rises above the trees: The image of PREPONDERANCE OF THE GREAT. Thus the superior man, when he stands alone, Is unconcerned, And if he has to renounce the world, He is undaunted.",
	},
	{
		key: "010010",
		hex: "\u4DDC",
		name: "K'an",
		character: "\u574E",
		title: "The Abysmal (Water)",
		judgement:
			"The Abysmal repeated. If you are sincere, you have success in your heart, And whatever you do succeeds.",
		image: "Water flows on uninterruptedly and reaches its goal: The image of the Abysmal repeated. Thus the superior man walks in lasting virtue And carries on the business of teaching.",
	},
	{
		key: "101101",
		hex: "\u4DDD",
		name: "Li",
		character: "\u96E2",
		title: "The Clinging (Fire)",
		judgement:
			"THE CLINGING. Perseverance furthers. It brings success. Care of the cow brings good fortune.",
		image: "That which is bright rises twice: The image of FIRE. Thus the great man, by perpetuating this brightness, Illumines the four quarters of the world.",
	},
	{
		key: "001110",
		hex: "\u4DDE",
		name: "Hsien",
		character: "\u54B8",
		title: "Influence (Wooing)",
		judgement:
			"INFLUENCE. Success. Perseverance furthers. To take a maiden to wife brings good fortune. Commentary on the Decision",
		image: "A lake on the mountain: The image of influence. Thus the superior man encourages people to approach him By his readiness to receive them.",
	},
	{
		key: "011100",
		hex: "\u4DDF",
		name: "He\u0302ng",
		character: "\u6046",
		title: "Duration",
		judgement:
			"DURATION. Success. No blame. Perseverance furthers. It furthers one to have somewhere to go.",
		image: "Thunder and wind: the image of DURATION. Thus the superior man stands firm And does not change his direction.",
	},
	{
		key: "001111",
		hex: "\u4DE0",
		name: "Tun",
		character: "\u906F",
		title: "Retreat",
		judgement: "RETREAT. Success. In what is small, perseverance furthers.",
		image: "Mountain under heaven: the image of RETREAT. Thus the superior man keeps the inferior man at a distance, Not angrily but with reserve.",
	},
	{
		key: "111100",
		hex: "\u4DE1",
		name: "Ta Chuang",
		character: "\u5927 \u58EF",
		title: "The Power of the Great",
		judgement: "THE POWER OF THE GREAT. Perseverance furthers.",
		image: "Thunder in heaven above: The image of THE POWER OF THE GREAT. Thus the superior man does not tread upon paths That do not accord with established order.",
	},
	{
		key: "000101",
		hex: "\u4DE2",
		name: "Chin",
		character: "\u6649",
		title: "Progress",
		judgement:
			"PROGRESS. The powerful prince Is honored with horses in large numbers. In a single day he is granted audience three times.",
		image: "The sun rises over the earth: The image of PROGRESS. Thus the superior man himself Brightens his bright virtue.",
	},
	{
		key: "101000",
		hex: "\u4DE3",
		name: "Ming I",
		character: "\u660E \u5937",
		title: "Darkening of the Light",
		judgement:
			"DARKENING OF THE LIGHT. In adversity It furthers one to be persevering.",
		image: "The light has sunk into the earth: The image of DARKENING OF THE LIGHT. Thus does the superior man live with the great mass: He veils his light, yet still shines.",
	},
	{
		key: "101011",
		hex: "\u4DE4",
		name: "Chia Je\u0302n",
		character: "\u5BB6 \u4EBA",
		title: "The Family (Clan)",
		judgement: "THE FAMILY. The perseverance of the woman furthers.",
		image: "The image of THE FAMILY. Thus the superior man has substance in his words And duration in his way of life.",
	},
	{
		key: "110101",
		hex: "\u4DE5",
		name: "K'uei",
		character: "\u777D",
		title: "Opposition",
		judgement:
			"OPPOSITION. In small matters, good fortune. Commentary on the Decision OPPOSITION: fire moves upward, the lake moves downward. Two daughters live together, but their minds are not directed to common concerns.",
		image: "Above, fire; below, the lake: The image of OPPOSITION. Thus amid all fellowship The superior man retains his individuality.",
	},
	{
		key: "001010",
		hex: "\u4DE6",
		name: "Chien",
		character: "\u8E47",
		title: "Obstruction",
		judgement:
			"OBSTRUCTION. The southwest furthers. The northeast does not further. It furthers one to see the great man. Perseverance brings good fortune. Commentary on the Decision",
		image: "Water on the mountain: The image of OBSTRUCTION. Thus the superior man turns his attention to himself And molds his character.",
	},
	{
		key: "010100",
		hex: "\u4DE7",
		name: "Hsieh",
		character: "\u89E3",
		title: "Deliverance",
		judgement:
			"DELIVERANCE. The southwest furthers. If there is no longer anything where one has to go, Return brings good fortune. If there is still something where one has to go, Hastening brings good fortune.",
		image: "Thunder and rain set in: The image of DELIVERANCE. Thus the superior man pardons mistakes And forgives misdeeds.",
	},
	{
		key: "110001",
		hex: "\u4DE8",
		name: "Sun",
		character: "\u640D",
		title: "Decrease",
		judgement:
			"DECREASE combined with sincerity Brings about supreme good fortune Without blame. One may be persevering in this. It furthers one to undertake something. How is this to be carried out? One may use two small bowls for the sacrifice.",
		image: "At the foot of the mountain, the lake: The image of DECREASE. Thus the superior man controls his anger And restrains his instincts.",
	},
	{
		key: "100011",
		hex: "\u4DE9",
		name: "I",
		character: "\u76CA",
		title: "Increase",
		judgement:
			"INCREASE. It furthers one To undertake something. It furthers one to cross the great water.",
		image: "Wind and thunder: the image of INCREASE. Thus the superior man: If he sees good, he imitates it; If he has faults, he rids himself of them.",
	},
	{
		key: "000001",
		hex: "\u4DEA",
		name: "Kuai",
		character: "\u592C",
		title: "Breakthrough/Resoluteness",
		judgement:
			"BREAK-THROUGH. One must resolutely make the matter known At the court of the king. It must be announced truthfully. Danger. It is necessary to notify one’s own city. It does not further to resort to arms. It furthers one to undertake something.",
		image: "The lake has risen up to heaven: The image of BREAK-THROUGH. Thus the superior man Dispenses riches downward And refrains from resting on his virtue.",
	},
	{
		key: "011111",
		hex: "\u4DEB",
		name: "Kou",
		character: "\u592C",
		character: "\u59E4",
		title: "Coming to Meet",
		judgement:
			"COMING TO MEET. The maiden is powerful. One should not marry such a maiden",
		image: "Under heaven, wind: The image of COMING TO MEET. Thus does the prince act when disseminating his commands And proclaiming them to the four quarters of heaven",
	},
	{
		key: "000110",
		hex: "\u4DEC",
		name: "Ts'ui",
		character: "\u8403",
		title: "Gathering Together",
		judgement:
			"GATHERING TOGETHER. Success. The king approaches his temple. It furthers one to see the great man. This brings success. Perseverance furthers. To bring great offerings creates good fortune. It furthers one to undertake something.",
		image: "Over the earth, the lake: The image of GATHERING TOGETHER. Thus the superior man renews his weapons In order to meet the unforeseen.",
	},
	{
		key: "011000",
		hex: "\u4DED",
		name: "She\u0302ng",
		character: "\u5347",
		title: "Pushing Upwards",
		judgement:
			"PUSHING UPWARD has supreme success. One must see the great man. Fear not. Departure toward the south Brings good fortune.",
		image: "Within the earth, wood grows: The image of PUSHING UPWARD. Thus the superior man of devoted character Heaps up small things In order to achieve something high and great.",
	},
	{
		key: "010110",
		hex: "\u4DEE",
		name: "K'un",
		character: "\u56F0",
		title: "Oppression/Exhaustion",
		judgement:
			"OPPPRESSION. Success. Perseverance. The great man brings about good fortune. No blame. When one has something to say, It is not believed.",
		image: "There is no water in the lake: The image of EXHAUSTION. Thus the superior man stakes his life On following his will.",
	},
	{
		key: "011010",
		hex: "\u4DEF",
		name: "Ching",
		character: "\u4E95",
		title: "The Well",
		judgement:
			"THE WELL. The town may be changed, But the well cannot be changed. It neither decreases nor increases. They come and go and draw from the well. If one gets down almost to the water And the rope does not go all the way, Or the jug breaks, it brings misfortune.",
		image: "Water over wood: the image of THE WELL. Thus the superior man encourages the people at their work, And exhorts them to help one another.",
	},
	{
		key: "101110",
		hex: "\u4DF0",
		name: "Ko",
		character: "\u9769",
		title: "Revolution/Molting",
		judgement:
			"REVOLUTION. On your own day You are believed. Supreme success, Furthering through perseverance. Remorse disappears.",
		image: "Fire in the lake: the image of REVOLUTION. Thus the superior man Sets the calendar in order And makes the seasons clear.",
	},
	{
		key: "011101",
		hex: "\u4DF1",
		name: "Ting",
		character: "\u9F0E",
		title: "The Cauldron",
		judgement: "THE CAULDRON. Supreme good fortune. Success",
		image: "Fire over wood: The image of THE CAULDRON. Thus the superior man consolidates his fate By making his position correct.",
	},
	{
		key: "100100",
		hex: "\u4DF2",
		name: "Che\u0302n",
		character: "\u9707",
		title: "The Arousing (Shock/Thunder)",
		judgement:
			"SHOCK brings success. Shock comes—oh, oh! Laughing words—ha, ha! The shock terrifies for a hundred miles, And he does not let fall the sacrificial spoon and chalice.",
		image: "Thunder repeated: the image of SHOCK. Thus in fear and trembling The superior man sets his life in order And examines himself.",
	},
	{
		key: "001001",
		hex: "\u4DF3",
		name: "Ke\u0302n",
		character: "\u826E",
		title: "Keeping Still/Mountain",
		judgement:
			"KEEPING STILL. Keeping his back still So that he no longer feels his body. He goes into his courtyard And does not see his people. No blame.",
		image: "Mountains standing close together: The image of KEEPING STILL. Thus the superior man Does not permit his thoughts To go beyond his situation.",
	},
	{
		key: "001011",
		hex: "\u4DF4",
		name: "Chien",
		character: "\u6F38",
		title: "Development/Gradual Progress",
		judgement:
			"DEVELOPMENT. The maiden Is given in marriage. Good fortune. Perseverance furthers.",
		image: "On the mountain, a tree: The image of DEVELOPMENT. Thus the superior man abides in dignity and virtue, In order to improve the mores.",
	},
	{
		key: "110100",
		hex: "\u4DF5",
		name: "Kuie Mei",
		character: "\u6B78 \u59B9",
		title: "The Marrying Maiden",
		judgement:
			"THE MARRYING MAIDEN. Undertakings bring misfortune. Nothing that would further.",
		image: "Thunder over the lake: The image of THE MARRYING MAIDEN. Thus the superior man Understands the transitory In the light of the eternity of the end.",
	},
	{
		key: "101100",
		hex: "\u4DF6",
		name: "Fe\u0302ng",
		character: "\u8C50",
		title: "Abundance/Fullness",
		judgement:
			"ABUNDANCE has success. The king attains abundance. Be not sad. Be like the sun at midday.",
		image: "Both thunder and lightning come: The image of ABUNDANCE. Thus the superior man decides lawsuits And carries out punishments.",
	},
	{
		key: "001101",
		hex: "\u4DF7",
		name: "Lu\u0308",
		character: "\u65C5",
		title: "The Wanderer",
		judgement:
			"THE WANDERER. Success through smallness. Perseverance brings good fortune To the wanderer.",
		image: "Fire on the mountain: The image of THE WANDERER. Thus the superior man Is clear-minded and cautious In imposing penalties, And protracts no lawsuits.",
	},
	{
		key: "011011",
		hex: "\u4DF8",
		name: "Sun",
		character: "\u5DFD",
		title: "The Gentle (Penetrating/Wind)",
		judgement:
			"THE GENTLE. Success through what is small. It furthers one to have somewhere to go. It furthers one to see the great man.",
		image: "Winds following one upon the other: The image of THE GENTLY PENETRATING. Thus the superior man Spreads his commands abroad And carries out his undertakings",
	},
	{
		key: "110110",
		hex: "\u4DF9",
		name: "Tui",
		character: "\u514C",
		title: "The Jouous/Lake",
		judgement: "THE JOYOUS. Success. Perseverance is favorable.",
		image: "Lakes resting one on the other: The image of THE JOYOUS. Thus the superior man joins with his friends For discussion and practice.",
	},
	{
		key: "010011",
		hex: "\u4DFA",
		name: "Huan",
		character: "\u6E19",
		title: "Dispersion/Dissolution",
		judgement:
			"DISPERSION. Success. The king approaches his temple. It furthers one to cross the great water. Perseverance furthers.",
		image: "The wind drives over the water: The image of DISPERSION. Thus the kings of old sacrificed to the Lord And built temples.",
	},
	{
		key: "110010",
		hex: "\u4DFB",
		name: "Chieh",
		character: "\u7BC0",
		title: "Limitation",
		judgement:
			"LIMITATION. Success. Galling limitation must not be persevered in.",
		image: "Water over lake: the image of LIMITATION. Thus the superior man Creates number and measure, And examines the nature of virtue and correct conduct.",
	},
	{
		key: "110011",
		hex: "\u4DFC",
		name: "Chung Fu",
		character: "\u4E2D \u5B5A",
		title: "Inner Truth",
		judgement:
			"Through being limited, things are made dependable. Hence there follows the hexagram of INNER TRUTH.",
		image: "INNER TRUTH. Pigs and fishes. Good fortune. It furthers one to cross the great water. Perseverance furthers.",
	},
	{
		key: "001100",
		hex: "\u4DFD",
		name: "Hsiah Kuo",
		character: "\u5C0F \u904E",
		title: "Preponderance of the Soul",
		judgement:
			"PREPONDERANCE OF THE SMALL. Success. Perseverance furthers. 1257 Small things may be done; great things should not be done. The flying bird brings the message: It is not well to strive upward, It is well to remain below. Great good fortune.",
		image: "Thunder on the mountain: The image of PREPONDERANCE OF THE SMALL. Thus in his conduct the superior man gives preponderance to reverence. In bereavement he gives preponderance to grief. In his expenditures he gives preponderance to thrift.",
	},
	{
		key: "101010",
		hex: "\u4DFE",
		name: "Chi Chi",
		character: "\u65E2 \u6FDF",
		title: "After Completion",
		judgement:
			"AFTER COMPLETION. Success in small matters. Perseverance furthers. At the beginning good fortune, At the end disorder.",
		image: "Water over fire: the image of the condition In AFTER COMPLETION. Thus the superior man Takes thought of misfortune And arms himself against it in advance.",
	},
	{
		key: "010101",
		hex: "\u4DFF",
		name: "Wei Chi",
		character: "\u672A \u6FDF",
		title: "Before Completion",
		judgement:
			"BEFORE COMPLETION. Success. But if the little fox, after nearly completing the crossing, Gets his tail in the water, There is nothing that would further.",
		image: "Fire over water: The image of the condition before transition. Thus the superior man is careful In the differentiation of things, So that each finds its place.",
	},

	{
		key: "11100",
		hex: "\u2630 \u268F",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "11000",
		hex: "\u2631 \u268F",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "10100",
		hex: "\u2632 \u268F",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "10000",
		hex: "\u2633 \u268F",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "01100",
		hex: "\u2634 \u268F",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "01000",
		hex: "\u2635 \u268F",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "00100",
		hex: "\u2636 \u268F",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "00000",
		hex: "\u2637 \u268F",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},

	{
		key: "11101",
		hex: "\u2630 \u268E",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "11001",
		hex: "\u2631 \u268E",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "10101",
		hex: "\u2632 \u268E",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "10001",
		hex: "\u2633 \u268E",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "01101",
		hex: "\u2634 \u268E",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "01001",
		hex: "\u2635 \u268E",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "00101",
		hex: "\u2636 \u268E",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "00001",
		hex: "\u2637 \u268E",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},

	{
		key: "11111",
		hex: "\u2630 \u268C",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "11011",
		hex: "\u2631 \u268C",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "10111",
		hex: "\u2632 \u268C",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "10011",
		hex: "\u2633 \u268C",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "01111",
		hex: "\u2634 \u268C",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "01011",
		hex: "\u2635 \u268C",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "00111",
		hex: "\u2636 \u268C",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "00011",
		hex: "\u2637 \u268C",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},

	{
		key: "11110",
		hex: "\u2630 \u268D",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "11010",
		hex: "\u2631 \u268D",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "10110",
		hex: "\u2632 \u268D",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "10010",
		hex: "\u2633 \u268D",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "01110",
		hex: "\u2634 \u268D",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "01010",
		hex: "\u2635 \u268D",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "00110",
		hex: "\u2636 \u268D",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "00010",
		hex: "\u2637 \u268D",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},

	{
		key: "1110",
		hex: "\u2630 \u268B",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "1100",
		hex: "\u2631 \u268B",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "1010",
		hex: "\u2632 \u268B",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "1000",
		hex: "\u2633 \u268B",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "0110",
		hex: "\u2634 \u268B",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "0100",
		hex: "\u2635 \u268B",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "0010",
		hex: "\u2636 \u268B",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "0000",
		hex: "\u2637 \u268B",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},

	{
		key: "1111",
		hex: "\u2630 \u268A",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "1101",
		hex: "\u2631 \u268A",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "1011",
		hex: "\u2632 \u268A",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "1001",
		hex: "\u2633 \u268A",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "0111",
		hex: "\u2634 \u268A",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "0101",
		hex: "\u2635 \u268A",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "0011",
		hex: "\u2636 \u268A",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "0001",
		hex: "\u2637 \u268A",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},

	{
		key: "111",
		hex: "\u2630",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "110",
		hex: "\u2631",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "101",
		hex: "\u2632",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "100",
		hex: "\u2633",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "011",
		hex: "\u2634",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "010",
		hex: "\u2635",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "001",
		hex: "\u2636",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "000",
		hex: "\u2637",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},

	{
		key: "11",
		hex: "\u268C",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "10",
		hex: "\u268D",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "01",
		hex: "\u268E",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "00",
		hex: "\u268F",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},

	{
		key: "1",
		hex: "\u268A",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
	{
		key: "0",
		hex: "\u268B",
		name: "",
		character: "",
		title: "",
		judgement: "",
		image: "",
	},
];
